services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 27017:27017
    networks:
      - dapr

  mongo-express:
    image: mongo-express
    container_name: mongodb-express
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017
      ME_CONFIG_BASICAUTH: false
    ports:
      - "33333:8081"
    networks:
      - dapr
    depends_on:
      - mongodb

  jaeger:
    image: jaegertracing/opentelemetry-all-in-one:latest
    ports:
      - 16686:16686
      - 13133:13133
      - 4317:4317
      - 4318:4318
    networks:
      - dapr

  cache:
    image: redis:7.2
    expose:
      - "6379"
    networks:
      - dapr

  seq:
    image: datalust/seq:latest
    container_name: seq
    volumes:
      - ./.containers/seq:/data
    environment:
      - ACCEPT_EULA=Y
    networks:
      - dapr
    ports:
      - 5341:5341
      - 7272:80
        
  postgresql:
    container_name: temporal-postgresql
    environment:
      POSTGRES_PASSWORD: temporal
      POSTGRES_USER: temporal
    image: postgres:latest
    networks:
      - dapr
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data

  ############################
  # Dapr placement service
  ############################
  placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"
    networks:
      - dapr

networks:
  dapr: null
