apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: payments
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
    - name: host
      value: "amqp://guest:guest@rabbitmq:5672"
    - name: durable
      value: "true"
    - name: autoAck
      value: "false"
    - name: deliveryMode
      value: "2"
    - name: reconnectWait
      value: "5s"
    - name: concurrencyMode
      value: "parallel"
scopes:
  - order-api
  - order-worker
  - payments