build:
	docker build -f application/frontend/Dockerfile-x86 -t frontend ../

tag-images:
	docker tag frontend aldosebastian/simple-pizza-winkel-frontend:latest

push:
	docker push aldosebastian/simple-pizza-winkel-frontend:latest

